<?php

/**
 * DmContact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    diem-project
 * @subpackage model
 * @author     Thibault D
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class DmContact extends PluginDmContact
{
}
