<?php

/**
 * DocPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    diemSite
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class DocPage extends BaseDocPage
{

  public function getMoreRecentText()
  {
    if($this->get('text'))
    {
      return $this->get('text');
    }

    return $this->getPreviousDocPage()->getMoreRecentText();
  }

  public function getPreviousDocPage()
  {
    return $this->getTable()->createQuery('p')
    ->withI18n()
    ->leftJoin('p.Doc d')
    ->leftJoin('d.Branch b')
    ->where('pTranslation.name = ?', $this->get('name'))
    ->andWhere('d.type = ?', $this->get('Doc')->get('type'))
    ->andWhere('b.number != ?', $this->get('Doc')->get('Branch')->get('number'))
    ->orderBy('b.number DESC')
    ->fetchOne();
  }
}
