<?php

/**
 * PluginBranch
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    diem-project
 * @subpackage model
 * @author     Thibault D
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class PluginBranch extends BasePluginBranch
{
}
