<?php

/**
 * Plugin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    diem-project
 * @subpackage model
 * @author     Thibault D
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class Plugin extends BasePlugin
{

  public function getGithubIssues($state = null)
  {
    $api = new phpGitHubApi();
    
    return $api->listIssues($this->getGithubUsername(), $this->getGithubRepo(), $state);
  }

  public function getGithubCommits()
  {
    $api = new phpGitHubApi();

    return $api->listBranchCommits($this->getGithubUsername(), $this->getGithubRepo(), 'master');
  }

  public function getGithubCloneUrl()
  {
    return str_replace('http://', 'git://', $this->get('github_url')).'.git';
  }

  public function getGithubUsername()
  {
    return preg_replace('|^http://github.com/([^/]+)/.+$|', '$1', $this->get('github_url'));
  }

  public function getGithubRepo()
  {
    return preg_replace('|^http://github.com/[^/]+/([^/]+)$|', '$1', $this->get('github_url'));
  }

  public function preSave($event)
  {
    $this->github_url = trim($this->github_url, '/');

    return parent::preSave($event);
  }
  
  public function getBrancheNumbers()
  {
    $numbers = array();
    
    foreach($this->get('Branches') as $branch)
    {
      $numbers[] = $branch->get('number');
    }
    
    return $numbers;
  }
  
}
