<?php

/**
 * SnippetComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    diem-project
 * @subpackage model
 * @author     Thibault D
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class SnippetComment extends BaseSnippetComment
{
}
