<?php

/**
 * Snippet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    diem-project
 * @subpackage model
 * @author     Thibault D
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Snippet extends BaseSnippet
{
  
  public function preSave($event)
  {
    parent::preSave($event);
    
    if (!$this->hash)
    {
      $this->hash = dmString::random(8);
    }
  }
  
  public function getMarkdownText(myGeshiMarkdown $markdown)
  {
    return $markdown->toHtml(dmString::escape($this->text, ENT_NOQUOTES));
  }
}
