<?php

/**
 * Version
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    diemSite
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6698 2009-11-10 17:58:02Z jwage $
 */
class Version extends BaseVersion
{
  public function getDownloadUrl()
  {
    if(($package = $this->get('Package')) && !$package->isNew())
    {
      return '/'.$package->getWebPath();
    }

    if($tag = $this->get('github_tag'))
    {
      return 'http://github.com/downloads/diem-project/diem/diem-'.$tag.'.tgz';
    }
  }
}
