<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('dm_error', 'klass');
        $this->removeColumn('dm_sent_mail', 'name');
        $this->removeColumn('dm_sent_mail', 'header');
        $this->removeColumn('dm_sent_mail', 'description');
        $this->removeColumn('dm_mail_template_translation', 'title');
        $this->addColumn('dm_error', 'php_class', 'string', '127', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_sent_mail', 'dm_mail_template_id', 'integer', '8', array(
             ));
        $this->addColumn('dm_sent_mail', 'subject', 'string', '5000', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_sent_mail', 'body', 'clob', '', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_sent_mail', 'from_email', 'string', '5000', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_sent_mail', 'to_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_sent_mail', 'cc_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_sent_mail', 'bcc_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_sent_mail', 'reply_to_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_sent_mail', 'sender_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_sent_mail', 'strategy', 'string', '255', array(
             ));
        $this->addColumn('dm_sent_mail', 'transport', 'string', '255', array(
             ));
        $this->addColumn('dm_sent_mail', 'culture', 'string', '16', array(
             ));
        $this->addColumn('dm_sent_mail', 'debug_string', 'clob', '', array(
             ));
        $this->addColumn('dm_mail_template_translation', 'subject', 'string', '5000', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_mail_template_translation', 'cc_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_mail_template_translation', 'bcc_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_mail_template_translation', 'reply_to_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_mail_template_translation', 'sender_email', 'string', '5000', array(
             ));
        $this->addColumn('dm_mail_template_translation', 'list_unsuscribe', 'string', '5000', array(
             ));
        $this->changeColumn('dm_setting', 'type', 'enum', '', array(
             'notnull' => '1',
             'values' => 
             array(
              0 => 'text',
              1 => 'boolean',
              2 => 'select',
              3 => 'textarea',
              4 => 'number',
              5 => 'datetime',
             ),
             'default' => 'text',
             ));
        $this->changeColumn('dm_mail_template_translation', 'body', 'clob', '', array(
             'notnull' => '1',
             ));
        $this->changeColumn('dm_mail_template_translation', 'from_email', 'string', '5000', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->addColumn('dm_error', 'klass', 'string', '127', array(
             'notnull' => '1',
             ));
        $this->addColumn('dm_sent_mail', 'name', 'string', '255', array(
             ));
        $this->addColumn('dm_sent_mail', 'header', 'string', '60000', array(
             ));
        $this->addColumn('dm_sent_mail', 'description', 'string', '60000', array(
             ));
        $this->addColumn('dm_mail_template_translation', 'title', 'string', '5000', array(
             ));
        $this->removeColumn('dm_error', 'php_class');
        $this->removeColumn('dm_sent_mail', 'dm_mail_template_id');
        $this->removeColumn('dm_sent_mail', 'subject');
        $this->removeColumn('dm_sent_mail', 'body');
        $this->removeColumn('dm_sent_mail', 'from_email');
        $this->removeColumn('dm_sent_mail', 'to_email');
        $this->removeColumn('dm_sent_mail', 'cc_email');
        $this->removeColumn('dm_sent_mail', 'bcc_email');
        $this->removeColumn('dm_sent_mail', 'reply_to_email');
        $this->removeColumn('dm_sent_mail', 'sender_email');
        $this->removeColumn('dm_sent_mail', 'strategy');
        $this->removeColumn('dm_sent_mail', 'transport');
        $this->removeColumn('dm_sent_mail', 'culture');
        $this->removeColumn('dm_sent_mail', 'debug_string');
        $this->removeColumn('dm_mail_template_translation', 'subject');
        $this->removeColumn('dm_mail_template_translation', 'cc_email');
        $this->removeColumn('dm_mail_template_translation', 'bcc_email');
        $this->removeColumn('dm_mail_template_translation', 'reply_to_email');
        $this->removeColumn('dm_mail_template_translation', 'sender_email');
        $this->removeColumn('dm_mail_template_translation', 'list_unsuscribe');
    }
}