<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('dm_sent_mail', 'dm_sent_mail_dm_mail_template_id_dm_mail_template_id', array(
             'name' => 'dm_sent_mail_dm_mail_template_id_dm_mail_template_id',
             'local' => 'dm_mail_template_id',
             'foreign' => 'id',
             'foreignTable' => 'dm_mail_template',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->addIndex('dm_sent_mail', 'dm_sent_mail_dm_mail_template_id', array(
             'fields' => 
             array(
              0 => 'dm_mail_template_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('dm_sent_mail', 'dm_sent_mail_dm_mail_template_id_dm_mail_template_id');
        $this->removeIndex('dm_sent_mail', 'dm_sent_mail_dm_mail_template_id', array(
             'fields' => 
             array(
              0 => 'dm_mail_template_id',
             ),
             ));
    }
}