<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('dm_user', 'forgot_password_code', 'string', '8', array(
             'unique' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('dm_user', 'forgot_password_code');
    }
}