<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('dm_user', 'uid', 'string', '8', array(
             'notnull' => '0',
             'unique' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('dm_user', 'uid');
    }
}