<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('dm_contact', 'body', 'clob', '', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}